// Jobs Data - Each job has a unique ID for URL routing
const jobsData = [
    {
        id: "devops-intern-streamline-001",
        title: "DevOps Engineer Intern",
        company: "Streamline Healthcare Solutions",
        companyShort: "Streamline",
        location: "India",
        salary: "₹15K - 30K/month",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "January 30, 2025",
        openings: 10,
        skills: ["DevOps", "CI/CD", "Docker", "Linux"],
        description: `<h3>About the Role</h3><p>Streamline Healthcare is hiring for the role of DevOps Engineer Intern. This is a great opportunity for freshers to gain hands-on experience in DevOps practices.</p><h3>Job Details</h3><ul><li>Job Role: DevOps Engineer Intern</li><li>Salary: ₹15K - ₹30K/month</li><li>Location: India</li><li>Education: BE/BTech</li><li>Batch: 2024 - 2026</li></ul>`,
        applyLink: "https://www.talentd.in/jobs/streamline-healthcare-is-hiring-devops-engineer-intern"
    },
    {
        id: "cyber-security-analyst-cloudsek-002",
        title: "Cyber Security Analyst",
        company: "CloudSEK",
        companyShort: "CloudSEK",
        location: "Bengaluru",
        salary: "₹8 - 12 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "2 days ago",
        deadline: "January 25, 2025",
        openings: 15,
        skills: ["Cyber Security", "Threat Analysis", "SIEM", "Network Security"],
        description: `<h3>About the Role</h3><p>CloudSEK is hiring for the position of Cyber Security Analyst in Bengaluru. They are looking for candidates from recent batches to join their security team.</p><h3>Job Details</h3><ul><li>Job Role: Cyber Security Analyst</li><li>Salary: ₹8 - 12 LPA</li><li>Location: Bengaluru</li><li>Education: Bachelor's Degree</li><li>Batch: 2023 - 2025</li></ul>`,
        applyLink: "https://www.talentd.in/jobs/cyber-security-analyst-jobs-at-cloudsek-bengaluru-apply-now-8-12-lpa"
    },
    {
        id: "data-engineer-intern-fam-003",
        title: "Data Engineer Intern",
        company: "Fam",
        companyShort: "Fam",
        location: "Bengaluru",
        salary: "₹25K - 50K/month",
        type: "Internship",
        experience: "Fresher",
        category: "data",
        posted: "1 day ago",
        deadline: "January 20, 2025",
        openings: 5,
        skills: ["Python", "SQL", "Data Engineering", "ETL"],
        description: `<h3>About the Role</h3><p>Fam is looking for a Data Engineer Intern in Bengaluru. This internship offers a high stipend and is open to recent graduates.</p><h3>Job Details</h3><ul><li>Job Role: Data Engineer Intern</li><li>Salary: ₹25K - ₹50K/month</li><li>Location: Bengaluru</li><li>Education: BE/BTech</li><li>Batch: 2023 - 2025</li></ul>`,
        applyLink: "https://www.talentd.in/jobs/data-engineer-intern-hiring-at-fam-bengaluru-3-6-lpa"
    },
    {
        id: "software-developer-oracle-004",
        title: "Software Developer",
        company: "Oracle",
        companyShort: "Oracle",
        location: "Bengaluru",
        salary: "₹6 - 10 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "3 days ago",
        deadline: "January 28, 2025",
        openings: 50,
        skills: ["Java", "SQL", "OOP", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Oracle is hiring freshers for the Software Developer role. This is a high-paying opportunity for recent graduates with strong coding skills.</p><h3>Job Details</h3><ul><li>Job Role: Software Developer</li><li>Salary: ₹6 - 10 LPA</li><li>Location: Bengaluru</li><li>Education: Bachelor's Degree</li><li>Batch: 2023 - 2025</li></ul>`,
        applyLink: "https://www.talentd.in/jobs/software-developer-jobs-at-oracle-bengaluru-apply-now-6-10-lpa"
    },
    {
        id: "l1-service-desk-zones-005",
        title: "L1 Service Desk",
        company: "Zones",
        companyShort: "Zones",
        location: "Bengaluru",
        salary: "₹3 - 3.5 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "2 days ago",
        deadline: "January 22, 2025",
        openings: 30,
        skills: ["IT Support", "Troubleshooting", "Communication", "Windows"],
        description: `<h3>About the Role</h3><p>Zones is hiring IT freshers for the L1 Service Desk role. This is an entry-level position suitable for those starting their career in IT support.</p><h3>Job Details</h3><ul><li>Job Role: L1 Service Desk</li><li>Salary: ₹3 - 3.5 LPA</li><li>Location: Bengaluru</li><li>Education: Bachelor's Degree</li><li>Batch: 2024 - 2025</li></ul>`,
        applyLink: "https://www.talentd.in/jobs/l1-service-desk-jobs-at-zones-bangalore-apply-now-3-3-5-lpa"
    },
    {
        id: "software-developer-intern-ibm-006",
        title: "Software Developer Intern",
        company: "IBM",
        companyShort: "IBM",
        location: "Hyderabad, Bangalore",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "February 15, 2025",
        openings: 25,
        skills: ["Programming", "Data Structures", "Problem Solving", "Java/Python"],
        description: `<h3>About the Role</h3><p>IBM is hiring interns for their Software Developer role to work on next-generation data processing platforms.</p><h3>Job Details</h3><ul><li>Job Role: Software Developer Intern</li><li>Location: Hyderabad, Bangalore</li><li>Education: Bachelor's Degree</li><li>Batch: Freshers / Current Students</li></ul>`,
        applyLink: "https://ibmglobal.avature.net/en_US/careers/JobDetail?jobId=66791"
    },
    {
        id: "automation-sre-intern-ibm-007",
        title: "Intern for Automation SRE",
        company: "IBM",
        companyShort: "IBM",
        location: "Bangalore",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "2 days ago",
        deadline: "February 10, 2025",
        openings: 15,
        skills: ["Python", "Ansible", "Shell Scripting", "Cloud"],
        description: `<h3>About the Role</h3><p>IBM is seeking automation-focused interns for Site Reliability Engineering involving scripting and cloud infrastructure.</p><h3>Job Details</h3><ul><li>Job Role: Intern for Automation SRE</li><li>Location: Bangalore</li><li>Education: Bachelor's Degree</li><li>Skills: Python, Ansible, Shell Scripting</li></ul>`,
        applyLink: "https://ibmglobal.avature.net/en_US/careers/JobDetail?jobId=81552&source=WEB_Search_INDIA"
    },
    {
        id: "backend-developer-intern-ibm-008",
        title: "Back-end Developer Intern",
        company: "IBM",
        companyShort: "IBM",
        location: "Bangalore",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "3 days ago",
        deadline: "February 8, 2025",
        openings: 20,
        skills: ["C", "C++", "Java", "Python"],
        description: `<h3>About the Role</h3><p>IBM is hiring interns for the z/OS support team to design productivity aids for mainframe infrastructure.</p><h3>Job Details</h3><ul><li>Job Role: Back-end Developer Intern</li><li>Location: Bangalore</li><li>Education: Bachelor's Degree</li><li>Skills: C, C++, Java, Python</li></ul>`,
        applyLink: "https://ibmglobal.avature.net/en_US/careers/JobDetail?jobId=62243&source=WEB_Search_INDIA"
    },
    {
        id: "software-engineering-intern-microsoft-009",
        title: "Software Engineering Intern",
        company: "Microsoft",
        companyShort: "Microsoft",
        location: "Bangalore",
        salary: "₹80K - 1.2L/month",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2025",
        openings: 100,
        skills: ["Programming", "Data Structures", "Algorithms", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Microsoft is hiring for Software Engineering Interns specifically for the batch of 2027 graduates.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineering Intern</li><li>Location: Bangalore</li><li>Education: Bachelor's Degree</li><li>Batch: 2027 Graduates</li></ul>`,
        applyLink: "https://apply.careers.microsoft.com/careers/job/1970393556625300"
    },
    {
        id: "data-science-intern-microsoft-010",
        title: "Data Science Intern",
        company: "Microsoft",
        companyShort: "Microsoft",
        location: "Bangalore",
        salary: "₹80K - 1.2L/month",
        type: "Internship",
        experience: "Fresher",
        category: "data",
        posted: "1 day ago",
        deadline: "March 15, 2025",
        openings: 50,
        skills: ["Python", "Machine Learning", "Statistics", "Data Analysis"],
        description: `<h3>About the Role</h3><p>Microsoft is looking for Data Science Interns for their Bangalore office from the 2027 graduating batch.</p><h3>Job Details</h3><ul><li>Job Role: Data Science Intern</li><li>Location: Bangalore</li><li>Education: Bachelor's Degree</li><li>Batch: 2027 Graduates</li></ul>`,
        applyLink: "https://apply.careers.microsoft.com/careers/job/1970393556625290"
    },
    {
        id: "product-management-intern-microsoft-011",
        title: "Product Management Intern",
        company: "Microsoft",
        companyShort: "Microsoft",
        location: "Hyderabad",
        salary: "₹80K - 1.2L/month",
        type: "Internship",
        experience: "Fresher",
        category: "hr",
        posted: "2 days ago",
        deadline: "March 15, 2025",
        openings: 30,
        skills: ["Product Strategy", "Communication", "Analytical Skills", "Leadership"],
        description: `<h3>About the Role</h3><p>Microsoft is hiring Product Management Interns based in Hyderabad for the class of 2027.</p><h3>Job Details</h3><ul><li>Job Role: Product Management Intern</li><li>Location: Hyderabad</li><li>Education: Bachelor's Degree</li><li>Batch: 2027 Graduates</li></ul>`,
        applyLink: "https://apply.careers.microsoft.com/careers/job/1970393556629980"
    },
    {
        id: "applied-science-intern-microsoft-012",
        title: "Applied Science Intern",
        company: "Microsoft",
        companyShort: "Microsoft",
        location: "Bangalore",
        salary: "₹80K - 1.2L/month",
        type: "Internship",
        experience: "Fresher",
        category: "data",
        posted: "2 days ago",
        deadline: "March 15, 2025",
        openings: 25,
        skills: ["Machine Learning", "Deep Learning", "Python", "Research"],
        description: `<h3>About the Role</h3><p>Microsoft is hiring Applied Science Interns for the 2027 batch in Bangalore.</p><h3>Job Details</h3><ul><li>Job Role: Applied Science Intern</li><li>Location: Bangalore</li><li>Education: Bachelor's Degree</li><li>Batch: 2027 Graduates</li></ul>`,
        applyLink: "https://apply.careers.microsoft.com/careers/job/1970393556625293"
    },
    {
        id: "software-engineer-intern-honeywell-013",
        title: "Intern - Software Engineer",
        company: "Honeywell",
        companyShort: "Honeywell",
        location: "Bangalore",
        salary: "₹33K - 75K/month",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "February 28, 2025",
        openings: 40,
        skills: ["Programming", "Software Development", "Problem Solving", "C++/Java"],
        description: `<h3>About the Role</h3><p>Honeywell is hiring interns for software engineering roles with a competitive stipend.</p><h3>Job Details</h3><ul><li>Job Role: Intern - Software Engineer</li><li>Salary: ₹33K - ₹75K/month</li><li>Location: Bangalore</li><li>Batch: 2026, 2027, 2028</li></ul>`,
        applyLink: "https://careers.honeywell.com/en/sites/Honeywell/jobs/preview/129081/?keyword=Intern+Bachelors+Software+Eng&location=India&locationId=300000000469485&locationLevel=country&mode=location"
    },
    {
        id: "software-development-engineer-adobe-014",
        title: "Software Development Engineer",
        company: "Adobe",
        companyShort: "Adobe",
        location: "Bangalore",
        salary: "₹15 - 25 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "2 days ago",
        deadline: "February 20, 2025",
        openings: 35,
        skills: ["Programming", "Data Structures", "Algorithms", "System Design"],
        description: `<h3>About the Role</h3><p>Adobe is hiring for Software Development Engineer roles for freshers and experienced candidates.</p><h3>Job Details</h3><ul><li>Job Role: Software Development Engineer</li><li>Location: Bangalore</li><li>Education: Bachelor's Degree</li><li>Experience: Freshers / Experienced</li></ul>`,
        applyLink: "https://careers.adobe.com/us/en/job/R161978/Software-Development-Engineer"
    },
    {
        id: "sde-1-csg-015",
        title: "SDE I (Remote)",
        company: "CSG",
        companyShort: "CSG",
        location: "Remote (India)",
        salary: "₹8 - 15 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "3 days ago",
        deadline: "February 15, 2025",
        openings: 20,
        skills: ["Programming", "Software Development", "Problem Solving", "APIs"],
        description: `<h3>About the Role</h3><p>CSG is hiring for the position of SDE I. This is a remote role for candidates in India.</p><h3>Job Details</h3><ul><li>Job Role: SDE I</li><li>Location: Remote (India)</li><li>Education: Bachelor's Degree</li><li>Experience: Entry Level</li></ul>`,
        applyLink: "https://csgi.wd5.myworkdayjobs.com/CSGCareers/job/India-Remote/SDE-I_30697"
    },
    {
        id: "backend-intern-joveo-176",
        title: "Backend Intern",
        company: "Joveo",
        companyShort: "Joveo",
        location: "India",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "February 28, 2026",
        openings: 5,
        skills: ["Backend Development", "Programming", "APIs", "Databases"],
        description: `<h3>About the Role</h3><p>Joveo is hiring for a Backend Intern role.</p><h3>Job Details</h3><ul><li>Job Role: Backend Intern</li><li>Location: India</li><li>Experience: Internship</li></ul>`,
        applyLink: "https://www.linkedin.com/jobs/view/4310292705"
    },
    {
        id: "intern-ibm-177",
        title: "Intern",
        company: "IBM",
        companyShort: "IBM",
        location: "India",
        salary: "₹30K - 40K/month",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "February 28, 2026",
        openings: 20,
        skills: ["Programming", "Problem Solving", "Technical Skills"],
        description: `<h3>About the Role</h3><p>IBM is hiring for an Intern role with a stipend.</p><h3>Job Details</h3><ul><li>Job Role: Intern</li><li>Stipend: ₹30K - ₹40K/month</li><li>Location: India</li><li>Experience: Internship</li></ul>`,
        applyLink: "https://ibmglobal.avature.net/en_US/careers/JobDetail?jobId=48177"
    },
    {
        id: "software-engineer-intern-stripe-178",
        title: "Software Engineer Intern",
        company: "Stripe",
        companyShort: "Stripe",
        location: "India",
        salary: "₹50K - 70K/month",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 15,
        skills: ["Programming", "Data Structures", "Algorithms", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Stripe is hiring Software Engineer Interns with a high stipend.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineer Intern</li><li>Stipend: ₹50K - ₹70K/month</li><li>Location: India</li><li>Experience: Internship</li></ul>`,
        applyLink: "https://stripe.com/jobs/listing/software-engineer-intern/6230907?gh_src=73vnei"
    },
    {
        id: "sde-1-rippling-179",
        title: "SDE 1",
        company: "Rippling",
        companyShort: "Rippling",
        location: "India",
        salary: "₹30 LPA",
        type: "Full Time",
        experience: "1 Year",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Programming", "Data Structures", "System Design", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Rippling is hiring for the SDE 1 role.</p><h3>Job Details</h3><ul><li>Job Role: SDE 1</li><li>Expected CTC: ₹30 LPA</li><li>Experience: 1 Year</li></ul>`,
        applyLink: "https://ats.rippling.com/rippling/jobs/cad9c4b8-9371-43b7-964f-f153ce0d4246"
    },
    {
        id: "sde-1-intuit-180",
        title: "SDE 1",
        company: "Intuit",
        companyShort: "Intuit",
        location: "India",
        salary: "₹30 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 20,
        skills: ["Programming", "Data Structures", "Algorithms", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Intuit is hiring freshers for the SDE 1 role.</p><h3>Job Details</h3><ul><li>Job Role: SDE 1</li><li>Expected CTC: ₹30 LPA</li><li>Experience: Fresher</li></ul>`,
        applyLink: "https://jobs.intuit.com/job/-/-/27595/87369446800"
    },
    {
        id: "software-engineer-newgrad-stripe-181",
        title: "Software Engineer (New Grad)",
        company: "Stripe",
        companyShort: "Stripe",
        location: "India",
        salary: "₹25 - 30 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 25,
        skills: ["Programming", "Data Structures", "Algorithms", "System Design"],
        description: `<h3>About the Role</h3><p>Stripe is hiring New Graduates for the Software Engineer role.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineer</li><li>Batch: New Graduates</li><li>Expected CTC: ₹25 - ₹30 LPA</li></ul>`,
        applyLink: "https://stripe.com/jobs/listing/software-engineering-new-grad/7176975?gh_src=73vnei"
    },
    {
        id: "associate-software-engineer-opentext-182",
        title: "Associate Software Engineer",
        company: "OpenText",
        companyShort: "OpenText",
        location: "India",
        salary: "₹15 - 25 LPA",
        type: "Full Time",
        experience: "1-3 Years",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 15,
        skills: ["Programming", "Software Development", "Problem Solving"],
        description: `<h3>About the Role</h3><p>OpenText is hiring for the Associate Software Engineer role.</p><h3>Job Details</h3><ul><li>Job Role: SDE 1 / Associate Software Engineer</li><li>Experience: 1 - 3 Years</li><li>Expected CTC: ₹15 - ₹25 LPA</li></ul>`,
        applyLink: "https://careers.opentext.com/us/en/job/OPJOPEUS49046EXTERNALENUS/Associate-Software-Engineer"
    },
    {
        id: "intern-carrier-183",
        title: "Intern",
        company: "Carrier",
        companyShort: "Carrier",
        location: "India",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Programming", "Problem Solving", "Technical Skills"],
        description: `<h3>About the Role</h3><p>Carrier is hiring for an Intern role.</p><h3>Job Details</h3><ul><li>Job Role: Intern</li><li>Experience: 0 - 2 Years</li></ul>`,
        applyLink: "https://jobs.carrier.com/en/job/-/-/29289/87299468528"
    },
    {
        id: "associate-software-engineer-aptiv-184",
        title: "Associate Software Engineer",
        company: "APTIV",
        companyShort: "APTIV",
        location: "Bangalore",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Programming", "Software Development", "Embedded Systems"],
        description: `<h3>About the Role</h3><p>APTIV is hiring for the Associate Software Engineer role.</p><h3>Job Details</h3><ul><li>Job Role: Associate Software Engineer</li><li>Location: Bangalore</li><li>Experience: 0 - 2 Years</li></ul>`,
        applyLink: "https://aptiv.wd5.myworkdayjobs.com/en-US/aptiv_careers/job/Bangalore-India/Associate-Software-Engineer_J000687535"
    },
    {
        id: "software-developer-atidan-185",
        title: "Software Developer",
        company: "Atidan Technologies",
        companyShort: "Atidan",
        location: "India",
        salary: "₹5 - 8 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 15,
        skills: ["Programming", "Software Development", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Atidan Technologies is hiring Software Developers (Freshers).</p><h3>Job Details</h3><ul><li>Job Role: Software Developer</li><li>Experience: Fresher</li><li>Expected Salary: ₹5 - ₹8 LPA</li></ul>`,
        applyLink: "https://atidantech.com/software-developer-fresher/"
    },
    {
        id: "software-developer-2-oracle-186",
        title: "Software Developer 2",
        company: "Oracle",
        companyShort: "Oracle",
        location: "India",
        salary: "₹15 - 25 LPA",
        type: "Full Time",
        experience: "0-2 Years",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 30,
        skills: ["Java", "SQL", "Programming", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Oracle is hiring for the Software Developer 2 role.</p><h3>Job Details</h3><ul><li>Job Role: Software Developer 2</li><li>Experience: 0 - 2 Years</li><li>Expected Salary: ₹15 - ₹25 LPA</li></ul>`,
        applyLink: "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/job/308341"
    },
    {
        id: "applied-science-phd-intern-microsoft-191",
        title: "Applied Sciences PhD Intern",
        company: "Microsoft",
        companyShort: "Microsoft",
        location: "Bangalore",
        salary: "₹80K - 1.2L/month",
        type: "Internship",
        experience: "PhD Student",
        category: "data",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Machine Learning", "Deep Learning", "Research", "Python"],
        description: `<h3>About the Role</h3><p>Microsoft is hiring Applied Sciences PhD Interns for the 2027 batch.</p><h3>Job Details</h3><ul><li>Job Role: Applied Sciences PhD Intern</li><li>Location: Bangalore</li><li>Batch: 2027 Graduates</li></ul>`,
        applyLink: "https://apply.careers.microsoft.com/careers/job/1970393556625301"
    },
    {
        id: "intern-wipro-192",
        title: "Intern L0",
        company: "Wipro",
        companyShort: "Wipro",
        location: "Bengaluru",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 50,
        skills: ["Programming", "Problem Solving", "Communication"],
        description: `<h3>About the Role</h3><p>Wipro is hiring Interns.</p><h3>Job Details</h3><ul><li>Job Role: Intern L0</li><li>Location: Bengaluru</li></ul>`,
        applyLink: "https://careers.wipro.com/job/Intern-L0-1-1/114240-en_US"
    },
    {
        id: "tech-intern-slb-193",
        title: "Tech Delivery FreshOut Intern",
        company: "Schlumberger (SLB)",
        companyShort: "SLB",
        location: "India",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 20,
        skills: ["Technical Skills", "Problem Solving", "Engineering"],
        description: `<h3>About the Role</h3><p>SLB is hiring Tech Interns.</p><h3>Job Details</h3><ul><li>Job Role: Tech Delivery FreshOut Intern</li><li>Batch: 2026 / 2027</li></ul>`,
        applyLink: "https://careers.slb.com/jobaddetail.aspx?id=TechDelivery_FreshOut_Intern"
    },
    {
        id: "technical-intern-hitachi-194",
        title: "Technical Intern",
        company: "Hitachi Digital Services",
        companyShort: "Hitachi",
        location: "India",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 25,
        skills: ["Technical Skills", "Programming", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Hitachi Digital Services is hiring Technical Interns.</p><h3>Job Details</h3><ul><li>Job Role: Technical Intern</li><li>Batch: 2025</li></ul>`,
        applyLink: "https://grnh.se/c6gwr2fd2us"
    },
    {
        id: "fullstack-engineer-intern-elucidata-195",
        title: "Full Stack Engineer Intern",
        company: "Elucidata",
        companyShort: "Elucidata",
        location: "Remote / Hybrid",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 5,
        skills: ["Full Stack Development", "JavaScript", "React", "Node.js"],
        description: `<h3>About the Role</h3><p>Elucidata is hiring Full Stack Engineer Interns.</p><h3>Job Details</h3><ul><li>Job Role: Full Stack Engineer Intern</li><li>Location: Remote / Hybrid</li></ul>`,
        applyLink: "https://www.linkedin.com/posts/rowhitswami_were-hiring-at-elucidata-fullstack-engineering-activity-7400511417663180800-oi2j"
    },
    {
        id: "ml-ai-engineer-intern-kuppismart-196",
        title: "ML / AI Engineer Intern",
        company: "KUPPISMART Solutions",
        companyShort: "KUPPISMART",
        location: "India",
        salary: "₹30K - 40K/month",
        type: "Internship",
        experience: "Fresher",
        category: "data",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Machine Learning", "AI", "Python", "Deep Learning"],
        description: `<h3>About the Role</h3><p>KUPPISMART Solutions is hiring ML / AI Engineer Interns.</p><h3>Job Details</h3><ul><li>Job Role: ML / AI Engineer Intern</li><li>Stipend: ₹30K - ₹40K/month</li><li>Batch: 2024 - 2027</li></ul>`,
        applyLink: "https://docs.google.com/forms/d/e/1FAIpQLSfh3zaFBHYsHkk-CYeuguaqpKBayuR6uFZQkYCKguzc9Vag4A/viewform"
    },
    {
        id: "data-engineer-intern-techmicra-197",
        title: "Data Engineer (Intern/Fresher)",
        company: "Techmicra Systems",
        companyShort: "Techmicra",
        location: "India",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "data",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Data Engineering", "Python", "SQL", "ETL"],
        description: `<h3>About the Role</h3><p>Techmicra Systems is hiring Data Engineers.</p><h3>Job Details</h3><ul><li>Job Role: Data Engineer (Intern/Fresher)</li><li>Experience: Freshers Eligible</li></ul>`,
        applyLink: "https://docs.google.com/forms/d/e/1FAIpQLSe_0lmdkaohYVIvVbp3E5mR2zAOQO_LIvsMAs9VFhnJ8wQUhw/viewform"
    },
    {
        id: "sde-1-amazon-198",
        title: "Software Dev Engineer I",
        company: "Amazon",
        companyShort: "Amazon",
        location: "India",
        salary: "₹20 - 35 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 50,
        skills: ["Programming", "Data Structures", "Algorithms", "System Design"],
        description: `<h3>About the Role</h3><p>Amazon is hiring for SDE I via University Talent Acquisition.</p><h3>Job Details</h3><ul><li>Job Role: Software Dev Engineer I</li><li>Experience: University Hiring</li></ul>`,
        applyLink: "https://www.amazon.jobs/en/jobs/3099245/software-dev-engineer-i-amazon-university-talent-acquisition?cmpid=DA_INAD200785B"
    },
    {
        id: "graduate-opportunity-johnsoncontrols-199",
        title: "Graduate Opportunity",
        company: "Johnson Controls",
        companyShort: "Johnson Controls",
        location: "India",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 20,
        skills: ["Engineering", "Technical Skills", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Johnson Controls is hiring for Graduate Opportunities.</p><h3>Job Details</h3><ul><li>Job Role: Graduate Opportunity</li></ul>`,
        applyLink: "https://jobs.johnsoncontrols.com/job/WD30254636?source=Appcast_Indeed_Organic"
    },
    {
        id: "multiple-openings-oracle-200",
        title: "Multiple Openings",
        company: "Oracle",
        companyShort: "Oracle",
        location: "India",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 100,
        skills: ["Programming", "Java", "SQL", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Oracle is hiring for multiple positions.</p><h3>Job Details</h3><ul><li>Job Role: Multiple Openings</li></ul>`,
        applyLink: "https://fa-eqzh-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/40000368"
    },
    {
        id: "qa-intern-intelehealth-201",
        title: "Intern - Quality Assurance",
        company: "Intelehealth",
        companyShort: "Intelehealth",
        location: "India",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 5,
        skills: ["QA Testing", "Manual Testing", "Bug Tracking", "Communication"],
        description: `<h3>About the Role</h3><p>Intelehealth is hiring QA Interns.</p><h3>Job Details</h3><ul><li>Job Role: Intern - Quality Assurance</li></ul>`,
        applyLink: "https://intelehealth.zohorecruit.com/jobs/Careers/783954000005170317/Intern---Quality-Assurance?source=CareerSite"
    },
    {
        id: "freshers-zycus-202",
        title: "Hiring Freshers",
        company: "Zycus",
        companyShort: "Zycus",
        location: "India",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 30,
        skills: ["Programming", "Problem Solving", "Communication"],
        description: `<h3>About the Role</h3><p>Zycus is hiring freshers.</p><h3>Job Details</h3><ul><li>Job Role: Hiring Freshers</li></ul>`,
        applyLink: "https://zycus.sensehq.com/careers/jobs/57436"
    },
    {
        id: "sdet-intern-browserstack-203",
        title: "Software Development Engineer in Test - Intern",
        company: "BrowserStack",
        companyShort: "BrowserStack",
        location: "Mumbai",
        salary: "Competitive",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Testing", "Automation", "Programming", "Problem Solving"],
        description: `<h3>About the Role</h3><p>BrowserStack is hiring SDET Interns from the 2026 batch.</p><h3>Job Details</h3><ul><li>Job Role: Software Development Engineer in Test - Intern</li><li>Location: Mumbai</li><li>Batch: 2026 Graduate</li></ul>`,
        applyLink: "https://browserstack.wd3.myworkdayjobs.com/External/job/Mumbai---Work-From-Office/Software-Development-Engineer-in-Test--Intern-Campus-2026-Graduate---Mumbai-WFO_JR102802?source=LinkedIn"
    },
    {
        id: "software-engineer-2-mastercard-204",
        title: "Software Engineer II",
        company: "Mastercard",
        companyShort: "Mastercard",
        location: "India",
        salary: "₹15 - 25 LPA",
        type: "Full Time",
        experience: "1-2 Years",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 20,
        skills: ["Programming", "Software Development", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Mastercard is hiring for the Software Engineer II role.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineer II</li></ul>`,
        applyLink: "https://careers.mastercard.com/us/en/job/MASRUSR261171EXTERNALENUS/Software-Engineer-II-1?utm_source=linkedin&utm_medium=phenom-feeds&source=LINKEDIN"
    },
    {
        id: "freshers-infilect-205",
        title: "Hiring Freshers",
        company: "Infilect",
        companyShort: "Infilect",
        location: "India",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 15,
        skills: ["Programming", "Problem Solving", "Technical Skills"],
        description: `<h3>About the Role</h3><p>Infilect is hiring freshers.</p><h3>Job Details</h3><ul><li>Job Role: Hiring Freshers</li></ul>`,
        applyLink: "https://infilect.keka.com/careers/jobdetails/31397?source=linkedin"
    },
    {
        id: "engineering-roles-qualcomm-206",
        title: "Engineering Roles",
        company: "Qualcomm",
        companyShort: "Qualcomm",
        location: "India",
        salary: "₹15 - 30 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 50,
        skills: ["Engineering", "Programming", "Embedded Systems", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Qualcomm is hiring for Engineering Roles.</p><h3>Job Details</h3><ul><li>Job Role: Engineering Roles</li></ul>`,
        applyLink: "https://careers.qualcomm.com/careers/job/446714421802?hl=en-US&domain=qualcomm.com&source=APPLICANT_SOURCE-6-2"
    },
    {
        id: "associate-techmahindra-207",
        title: "Associate",
        company: "Tech Mahindra",
        companyShort: "Tech Mahindra",
        location: "Pune",
        salary: "Competitive",
        type: "Full Time",
        experience: "0-5 Years",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 40,
        skills: ["Technical Skills", "Communication", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Tech Mahindra is hiring Associates.</p><h3>Job Details</h3><ul><li>Job Role: Associate</li><li>Experience: 0 - 5 Years</li></ul>`,
        applyLink: "https://www.naukri.com/job-listings-associate-tech-mahindra-pune-0-to-5-years-261125038942?src=drecomm_dashboard_profile"
    },
    {
        id: "service-desk-analyst-wipro-208",
        title: "Service Desk Analyst L1",
        company: "Wipro",
        companyShort: "Wipro",
        location: "Bengaluru",
        salary: "₹3 - 5 LPA",
        type: "Full Time",
        experience: "0-4 Years",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 30,
        skills: ["IT Support", "Communication", "Troubleshooting", "Customer Service"],
        description: `<h3>About the Role</h3><p>Wipro is hiring Service Desk Analysts.</p><h3>Job Details</h3><ul><li>Job Role: Service Desk Analyst L1</li><li>Location: Bengaluru</li><li>Experience: 0 - 4 Years</li></ul>`,
        applyLink: "https://www.naukri.com/job-listings-service-desk-analyst-l1-wipro-limited-bengaluru-0-to-4-years-271125926251?src=drecomm_dashboard_profile"
    },
    {
        id: "get-marketing-fosroc-209",
        title: "Graduate Engineer Trainee (Marketing)",
        company: "Fosroc",
        companyShort: "Fosroc",
        location: "Bengaluru",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "marketing",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Marketing", "Communication", "Sales", "Engineering"],
        description: `<h3>About the Role</h3><p>Fosroc is hiring Graduate Engineer Trainees in Marketing.</p><h3>Job Details</h3><ul><li>Job Role: Graduate Engineer Trainee (Marketing)</li><li>Location: Bengaluru</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://www.naukri.com/job-listings-trainee-graduate-engineer-trainee-marketing-bengaluru-fosroc-chemicals-bengaluru-0-to-1-years-241125024720?src=drecomm_dashboard_profile"
    },
    {
        id: "cyber-consultant-grantthornton-210",
        title: "Cyber Consultant",
        company: "Grant Thornton",
        companyShort: "Grant Thornton",
        location: "India",
        salary: "₹8 - 13.6 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 15,
        skills: ["Cyber Security", "Consulting", "Risk Assessment", "Communication"],
        description: `<h3>About the Role</h3><p>Grant Thornton is hiring Cyber Consultants.</p><h3>Job Details</h3><ul><li>Job Role: Cyber Consultant</li><li>Experience: 0 - 1 Years</li><li>Expected Salary: ₹8 - ₹13.6 LPA</li></ul>`,
        applyLink: "https://unstop.com/o/cp2iynG?lb=1H7alqM&utm_medium=Share&utm_source=saicharan45&utm_campaign=Jobs"
    },
    {
        id: "software-engineer-uipath-211",
        title: "Software Engineer",
        company: "UiPath",
        companyShort: "UiPath",
        location: "India",
        salary: "₹15 - 30 LPA",
        type: "Full Time",
        experience: "1 Year",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 20,
        skills: ["Programming", "Software Development", "RPA", "Problem Solving"],
        description: `<h3>About the Role</h3><p>UiPath is hiring Software Engineers.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineer</li><li>Experience: 1 Year</li><li>Expected Salary: ₹15 - ₹30 LPA</li></ul>`,
        applyLink: "https://jobs.ashbyhq.com/uipath/1cd7ed0d-07a2-494b-9518-b5c038427b56"
    },
    {
        id: "graduate-trainee-calix-212",
        title: "Graduate Trainee",
        company: "Calix",
        companyShort: "Calix",
        location: "Bangalore",
        salary: "₹4 - 7 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 15,
        skills: ["Programming", "Problem Solving", "Communication"],
        description: `<h3>About the Role</h3><p>Calix is hiring Graduate Trainees.</p><h3>Job Details</h3><ul><li>Job Role: Graduate Trainee</li><li>Location: Bangalore</li><li>Experience: 0 - 1 Years</li><li>Expected Salary: ₹4 - ₹7 LPA</li></ul>`,
        applyLink: "https://calix.wd1.myworkdayjobs.com/ExternalInternational/job/Bangalore/Graduate-Trainee_R-10780?source=LinkedIn"
    },
    {
        id: "associate-software-engineer-dentsu-213",
        title: "Associate Software Engineer",
        company: "Dentsu",
        companyShort: "Dentsu",
        location: "Mumbai",
        salary: "₹6 - 12 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Programming", "Software Development", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Dentsu is hiring Associate Software Engineers.</p><h3>Job Details</h3><ul><li>Job Role: Associate Software Engineer</li><li>Location: Mumbai</li><li>Experience: 0 - 1 Years</li><li>Expected Salary: ₹6 - ₹12 LPA</li></ul>`,
        applyLink: "https://dentsuaegis.wd3.myworkdayjobs.com/DAN_GLOBAL/job/DGS-India---Mumbai---Goregaon-Prism-Tower/Associate-Software-Engineer_R1105461?source=LinkedIn"
    },
    {
        id: "web-developer-emmvee-214",
        title: "Web Developer",
        company: "Emmvee Group",
        companyShort: "Emmvee",
        location: "India",
        salary: "₹4 - 7 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 5,
        skills: ["Web Development", "HTML", "CSS", "JavaScript"],
        description: `<h3>About the Role</h3><p>Emmvee Group is hiring Web Developers.</p><h3>Job Details</h3><ul><li>Job Role: Web Developer</li><li>Experience: 0 - 1 Years</li><li>Expected Salary: ₹4 - ₹7 LPA</li></ul>`,
        applyLink: "https://www.linkedin.com/jobs/view/4341520951/"
    },
    {
        id: "service-desk-l1-zones-215",
        title: "Service Desk L1",
        company: "Zones",
        companyShort: "Zones",
        location: "India",
        salary: "₹3 - 5 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 25,
        skills: ["IT Support", "Communication", "Troubleshooting", "Customer Service"],
        description: `<h3>About the Role</h3><p>Zones is hiring for the Service Desk L1 role.</p><h3>Job Details</h3><ul><li>Job Role: Service Desk L1</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://forms.office.com/Pages/ResponsePage.aspx?id=Bghm2I3zoEym8Y3rfP6JcRbALi5H8NxIt9vKS8yH3VVUN1c0VVYwQjZCRUk3RElMODRDOFAwSUpXVi4u"
    },
    {
        id: "freshers-wipro-sim-216",
        title: "Freshers Role",
        company: "Wipro SIM",
        companyShort: "Wipro SIM",
        location: "India",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 50,
        skills: ["Programming", "Problem Solving", "Communication"],
        description: `<h3>About the Role</h3><p>Wipro SIM is hiring freshers.</p><h3>Job Details</h3><ul><li>Job Role: Freshers</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://app.joinsuperset.com/join/#/signup/student/jobprofiles/b6cb2f45-d57e-43be-b387-f9aacc8288fa"
    },
    {
        id: "service-desk-analyst-hcltech-217",
        title: "Service Desk Analyst",
        company: "HCLTech",
        companyShort: "HCLTech",
        location: "India",
        salary: "₹3 - 5 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 40,
        skills: ["IT Support", "Communication", "Troubleshooting", "Customer Service"],
        description: `<h3>About the Role</h3><p>HCLTech is hiring Service Desk Analysts.</p><h3>Job Details</h3><ul><li>Job Role: Service Desk Analyst</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://forms.office.com/pages/responsepage.aspx?id=N-edGDrJWk-LaG9MqZQZElCAazGQaRZGsk4ipyNb95tUQ0cxVzNRNkpCWTU3SjZPTzlKTDVZMzVJSy4u&route=shorturl"
    },
    {
        id: "freshers-wipro-wilp-218",
        title: "Freshers (WILP)",
        company: "Wipro WILP",
        companyShort: "Wipro WILP",
        location: "India",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 100,
        skills: ["Programming", "Problem Solving", "Communication"],
        description: `<h3>About the Role</h3><p>Wipro WILP is hiring freshers.</p><h3>Job Details</h3><ul><li>Job Role: Freshers</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://app.joinsuperset.com/join/#/signup/student/jobprofiles/6fa74b2d-cea6-4fb5-9ca9-5c1537da23c5"
    },
    {
        id: "devops-engineer-associate-deutschebank-219",
        title: "DevOps Engineer, Associate",
        company: "Deutsche Bank",
        companyShort: "Deutsche Bank",
        location: "India",
        salary: "₹10 - 18 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 15,
        skills: ["DevOps", "CI/CD", "Cloud", "Linux"],
        description: `<h3>About the Role</h3><p>Deutsche Bank is hiring Associate DevOps Engineers.</p><h3>Job Details</h3><ul><li>Job Role: DevOps Engineer, Associate</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://careers.db.com/professionals/search-roles/?test.html%3Fkid%3D=linkedinjobwrap#/professional/job/66485"
    },
    {
        id: "software-engineer-hpe-220",
        title: "Software Engineer",
        company: "HPE",
        companyShort: "HPE",
        location: "India",
        salary: "₹8 - 15 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 25,
        skills: ["Programming", "Software Development", "Problem Solving"],
        description: `<h3>About the Role</h3><p>HPE is hiring Software Engineers.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineer</li><li>Experience: 0 - 1 Years</li><li>Expected Salary: ₹8 - ₹15 LPA</li></ul>`,
        applyLink: "https://careers.hpe.com/us/en/job/1197019/Software-Engineer"
    },
    {
        id: "software-engineer-optum-221",
        title: "Software Engineer",
        company: "Optum",
        companyShort: "Optum",
        location: "Hyderabad",
        salary: "₹10 - 15 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 20,
        skills: ["Programming", "Software Development", "Healthcare Tech"],
        description: `<h3>About the Role</h3><p>Optum is hiring Software Engineers.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineer</li><li>Location: Hyderabad</li><li>Experience: 0 - 1 Years</li><li>Expected Salary: ₹10 - ₹15 LPA</li></ul>`,
        applyLink: "https://careers.unitedhealthgroup.com/job/22557066/software-engineer-hyderabad-in/?src=JB-22455"
    },
    {
        id: "software-engineer-siemens-222",
        title: "Software Engineer",
        company: "Siemens",
        companyShort: "Siemens",
        location: "India",
        salary: "₹10 - 18 LPA",
        type: "Full Time",
        experience: "1-2 Years",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 20,
        skills: ["Programming", "Software Development", "Engineering"],
        description: `<h3>About the Role</h3><p>Siemens is hiring Software Engineers.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineer</li><li>Experience: 1 - 2 Years</li></ul>`,
        applyLink: "https://jobs.siemens.com/en_US/externaljobs/JobDetail/482618"
    },
    {
        id: "associate-engineer-bceglobal-223",
        title: "Associate Engineer",
        company: "BCE Global Tech",
        companyShort: "BCE Global",
        location: "India",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 15,
        skills: ["Programming", "Problem Solving", "Technical Skills"],
        description: `<h3>About the Role</h3><p>BCE Global Tech is hiring Associate Engineers.</p><h3>Job Details</h3><ul><li>Job Role: Associate Engineer</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://bceglobaltech.com/career-details/GTCFD-GRAD-051/Associate%20Engineer"
    },
    {
        id: "trainee-wipro-224",
        title: "Trainee",
        company: "Wipro",
        companyShort: "Wipro",
        location: "India",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 100,
        skills: ["Programming", "Problem Solving", "Communication"],
        description: `<h3>About the Role</h3><p>Wipro is hiring freshers as Trainees.</p><h3>Job Details</h3><ul><li>Job Role: Trainee</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://forms.office.com/pages/responsepage.aspx?id=5MSKJWoUHkGdyHmp4S_W2nL2OFqo7vtEkpvT1IBFJIRUQlNJMlk0T1BFTFUyOU5NMkxENkpYSFlEMy4u&route=shorturl"
    },
    {
        id: "contact-support-capgemini-225",
        title: "Contact Support Group",
        company: "Capgemini",
        companyShort: "Capgemini",
        location: "India",
        salary: "₹3 - 5 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 50,
        skills: ["Communication", "Customer Service", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Capgemini is hiring for the Contact Support Group.</p><h3>Job Details</h3><ul><li>Job Role: Contact Support Group</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://app.joinsuperset.com/join/#/signup/student/jobprofiles/3a776dbf-8e0a-48da-9bda-c26e442567be"
    },
    {
        id: "motion-graphic-designer-syncfusion-226",
        title: "Motion Graphic Designer",
        company: "Syncfusion",
        companyShort: "Syncfusion",
        location: "India",
        salary: "Competitive",
        type: "Full Time",
        experience: "Fresher",
        category: "design",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 5,
        skills: ["Motion Graphics", "Video Editing", "After Effects", "Design"],
        description: `<h3>About the Role</h3><p>Syncfusion is hiring Motion Graphic Designers.</p><h3>Job Details</h3><ul><li>Job Role: Motion Graphic Designer</li><li>Experience: 0 - 1 Years</li></ul>`,
        applyLink: "https://www.linkedin.com/posts/abilash-r-ux_hiring-motiongraphics-uxdesign-ugcPost-7399075096197378049-f4d4/"
    },
    {
        id: "software-engineering-ic2-microsoft-227",
        title: "Software Engineering IC2",
        company: "Microsoft",
        companyShort: "Microsoft",
        location: "India",
        salary: "₹14.8 - 22 LPA",
        type: "Full Time",
        experience: "1 Year",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 30,
        skills: ["Programming", "Data Structures", "Algorithms", "System Design"],
        description: `<h3>About the Role</h3><p>Microsoft is hiring for Software Engineering IC2 roles.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineering IC2</li><li>Experience: 1 Year</li><li>Expected Salary: ₹14.8 - ₹22 LPA</li></ul>`,
        applyLink: "https://unstop.gotrackier.io/click?campaign_id=1095&pub_id=33"
    },
    {
        id: "software-engineer-akamai-228",
        title: "Software Engineer",
        company: "Akamai",
        companyShort: "Akamai",
        location: "India",
        salary: "₹10 - 20 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 15,
        skills: ["Programming", "Cloud", "Networking", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Akamai is hiring Software Engineers.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineer</li><li>Experience: 0 - 1 Years</li><li>Expected Salary: ₹10 - ₹20 LPA</li></ul>`,
        applyLink: "https://fa-extu-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/2038"
    },
    {
        id: "software-engineer-1-ghx-229",
        title: "Software Engineer I",
        company: "GHX",
        companyShort: "GHX",
        location: "India",
        salary: "₹5 - 12 LPA",
        type: "Full Time",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 15, 2026",
        openings: 10,
        skills: ["Programming", "Software Development", "Problem Solving"],
        description: `<h3>About the Role</h3><p>GHX is hiring for Software Engineer I roles.</p><h3>Job Details</h3><ul><li>Job Role: Software Engineer I</li><li>Experience: 0 - 1 Years</li><li>Expected Salary: ₹5 - ₹12 LPA</li></ul>`,
        applyLink: "https://job-boards.greenhouse.io/globalhealthcareexchangeinc/jobs/4631021005?gh_src=a02044705us"
    },
    {
        id: "generative-ai-intern-evnek-230",
        title: "Generative AI Intern",
        company: "Evnek Technologies Pvt Ltd",
        companyShort: "Evnek",
        location: "Bangalore, Karnataka",
        salary: "Competitive Stipend",
        type: "Full Time",
        experience: "Fresher",
        category: "data",
        posted: "January 05, 2026",
        deadline: "March 30, 2026",
        openings: 5,
        skills: ["Python", "AI/ML", "NumPy", "Pandas", "Scikit-learn", "TensorFlow", "NLP"],
        description: `<h3>About the Role</h3><p>Evnek Technologies Pvt Ltd is looking for a passionate and motivated AI Intern to join their team. This internship offers hands-on experience in Artificial Intelligence and Machine Learning, providing exposure to real-world projects and industry practices.</p><h3>Key Responsibilities</h3><ul><li>Assist in developing and testing AI/ML models</li><li>Work with data collection, cleaning, and preprocessing</li><li>Support implementation of algorithms related to machine learning, NLP, or computer vision</li><li>Collaborate with the development team on AI-driven solutions</li></ul><h3>Job Details</h3><ul><li>Job Role: Generative AI Intern</li><li>Experience: 0-1 Year</li><li>Location: Remote – Bangalore</li><li>Industry: IT Services</li></ul>`,
        applyLink: "https://career.evnek.com/jobs/Careers/126220000015723175/Generative-AI-Intern?source=CareerSite"
    },
    {
        id: "backend-intern-primetrace-231",
        title: "Backend Intern",
        company: "Primetrace Technologies",
        companyShort: "Primetrace",
        location: "Bangalore",
        salary: "Competitive Stipend",
        type: "Internship",
        experience: "Fresher",
        category: "it",
        posted: "1 day ago",
        deadline: "March 30, 2026",
        openings: 5,
        skills: ["Node.js", "Go", "APIs", "Redis", "SQL", "Problem Solving"],
        description: `<h3>About the Role</h3><p>Primetrace Technologies is hiring Full-Stack Software Engineering Interns for a 6-month, full-time, work-from-office internship. This is a great opportunity for passionate developers who love building real things.</p><h3>What You'll Do</h3><ul><li>Work on real production systems</li><li>Debug real-world issues</li><li>Build features used by real users</li></ul><h3>Job Details</h3><ul><li>Job Role: Backend Intern</li><li>Duration: 6 months</li><li>Type: Full-time, Work-from-office</li><li>Location: Bangalore</li></ul>`,
        applyLink: "https://primetrace.keka.com/careers/jobdetails/53199"
    }
];

// Function to get all jobs
function getAllJobs() {
    return jobsData;
}

// Function to get job by ID
function getJobById(id) {
    return jobsData.find(job => job.id === id);
}

// Function to get jobs by category
function getJobsByCategory(category) {
    return jobsData.filter(job => job.category === category);
}

// Function to search jobs
function searchJobs(query, location) {
    return jobsData.filter(job => {
        const matchesQuery = !query || 
            job.title.toLowerCase().includes(query.toLowerCase()) ||
            job.company.toLowerCase().includes(query.toLowerCase()) ||
            job.skills.some(skill => skill.toLowerCase().includes(query.toLowerCase()));
        
        const matchesLocation = !location ||
            job.location.toLowerCase().includes(location.toLowerCase());
        
        return matchesQuery && matchesLocation;
    });
}

// Function to get featured jobs (first 6)
function getFeaturedJobs() {
    return jobsData.slice(0, 6);
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { jobsData, getAllJobs, getJobById, getJobsByCategory, searchJobs, getFeaturedJobs };
}
